/* Generated By:JavaCC: Do not edit this line. ZcodeConstants.java */
package com.javacc.zcode;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ZcodeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGITS = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int LBPAREN = 8;
  /** RegularExpression Id. */
  int RBPAREN = 9;
  /** RegularExpression Id. */
  int ADD = 10;
  /** RegularExpression Id. */
  int SUBTRACT = 11;
  /** RegularExpression Id. */
  int MULTIPLY = 12;
  /** RegularExpression Id. */
  int DIVIDE = 13;
  /** RegularExpression Id. */
  int EQUALS = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int SEMIC = 16;
  /** RegularExpression Id. */
  int SINGLE_QUOT = 17;
  /** RegularExpression Id. */
  int UNION = 18;
  /** RegularExpression Id. */
  int INTERSECT = 19;
  /** RegularExpression Id. */
  int SET_SUB = 20;
  /** RegularExpression Id. */
  int PRINT = 21;
  /** RegularExpression Id. */
  int PRINTLN = 22;
  /** RegularExpression Id. */
  int EOL = 23;
  /** RegularExpression Id. */
  int ID = 24;
  /** RegularExpression Id. */
  int LETTER = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER>",
    "<DIGITS>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\",\"",
    "\";\"",
    "\"\\\'\"",
    "<UNION>",
    "<INTERSECT>",
    "<SET_SUB>",
    "<PRINT>",
    "<PRINTLN>",
    "<EOL>",
    "<ID>",
    "<LETTER>",
  };

}
