/* Generated By:JavaCC: Do not edit this line. HelloConstants.java */
//像java�?样的包名定义,生成的java文件也会在此包下
package com.javacc.hello;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HelloConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HELLO = 4;
  /** RegularExpression Id. */
  int IDENTITY = 5;
  /** RegularExpression Id. */
  int EXCLAMATION = 6;
  /** RegularExpression Id. */
  int COMMA = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<HELLO>",
    "<IDENTITY>",
    "\"!\"",
    "\",\"",
  };

}
